server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root   /usr/share/nginx/html;

    location / {
        try_files $uri $uri.html $uri/index.html @nextssg;
    }

    location @nextssg {
        # Next.js SSG dynamic routes: /prefix/[param] → /prefix/_/index.html
        rewrite ^(/app/groups)/.*$ $1/_/index.html break;
        rewrite ^(/app/profile)/.*$ $1/_/index.html break;
        return 404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
